[package]
name = "format-url"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
